version: "3.9"

services:
  postgresql:
    container_name: postgresql
    image: postgres:15.1-bullseye
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: organizations
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5551:5432
